### ISSUE TITLE
Map gets randomly rotated and mirrored

### ISSUE THREAD

**Issue by jmacura** [hslayers/hslayers-ng#1498] opened 2021-01-18 14:19 UTC
Steps to reproduce:
1. open https://www.agrihub.cz/mapa
2. zoom to a random place
3. go to https://www.agrihub.cz main page
4. open "Výnosový potenciál" composition from the list below

![image](https://user-images.githubusercontent.com/5598693/104926080-faf58a80-599f-11eb-8dcc-5785e7229f93.png)

relates to version 1.27.2

Reported by @kcharvat in Firefox

**Comment by jmacura** [comment] 2021-01-18 23:25
I can reproduce it approx. in 1 of 15 attempts.
From the observations so far, it seems that _"something"_ is loaded too soon and the map won't get the correct `center` and `zoom`.

**Comment by kcharvat** [comment] 2021-01-19 07:14
For me in Firefox, it is very often, yesterday night, it was in every attempt. Now in 1 from 3

**Comment by raitisbe** [comment] 2021-01-21 13:34
For me the first link doesnt open. Seems like mime type config on the server, because for css it should not be text/html.

![image](https://user-images.githubusercontent.com/395514/105357942-2e355500-5bfe-11eb-98c8-4953678e716e.png)

**Comment by jmacura** [comment] 2021-01-21 23:06
> 
> 
> For me the first link doesnt open. Seems like mime type config on the server, because for css it should not be text/html.

Seems more like a Liferay bug to me. These content type mismatches with text/html usually happen when the target source does not exist (and the server responses with 404 error).

But this works fine for me (Firefox 84 @ Windows 10)... 😕

**Comment by kcharvat** [comment] 2021-02-03 06:47
Please is there any progress. This is for us now critical. We have next  week presentation of Innovation Hub and this is key functionality.  For me it is now biggest problem

**Comment by fzadrazil** [comment] 2021-02-03 14:01
Seems to be fixed by a combination of factors. Only some viewport parameters has been cloned from the default_view that caused maxZoom and other params to be ignored fbbbb91aae7779be2e01d2ab0dd7feb2189a02ca .
After setting extent constrain and multiWorlds=false, the issue doesn't appear anymore or is even harder to reproduce now.

**Closed by fzadrazil** 2021-02-03 14:01 UTC
Labels: bug
