### ISSUE TITLE
Ignore layer extent settings get ignored after another layer added

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#4497] opened 2023-11-21 16:22 UTC
# Bug

**Describe the bug**
A WMS settings to ignore layer extent is ignored after some other layer is added to the map via datasources panel.

**To Reproduce**
1. Add a WMS layer to the map, eg. https://watlas.lesprojekt.cz/client/geoserver/franta_wms/ows, layer "kraj_jinak"
2. The symbols are clipped by the extent of the WMS
3. Check "ignore layer extent", the whole symbols are now rendered as it should be
4. Add any other layer to the map
5. "Ignore layer extent" is still checked, but the symbols are clipped again.

**Expected behavior**
"Ignore layer extent" should be applied no matter what layers are added to the map.

**Comment by FilipLeitner** [comment] 2023-11-27 12:38
May be caused by clicking on 'Zoom to' of ignored layer which fails to find extent os it sets it (will be fixed)
Just adding new layer can not cause such a change in my opinion. 
Could it be that you have interacted with the layer in that way?

**Comment by fzadrazil** [comment] 2023-11-27 15:32
Hm, could be the case. And it is probably linked with another issue. There is no way to add Layman WMS without tiling, which leads to symbol clipping not just on the layer extent borders, but also on tile borders
![image](https://github.com/hslayers/hslayers-ng/assets/48727502/e1a3e236-1b85-4f6a-bd86-c31c34829566)

**Closed** 2023-12-10 14:49 UTC
Labels: bug
