### ISSUE TITLE
Wrong date in time slider for WMS-t in Firefox

### ISSUE THREAD

**Issue by fzadrazil** [hslayers/hslayers-ng#3126] opened 2022-06-16 09:44 UTC
# Bug

**Describe the bug**
The issue seems to turn up only in Firefox, it is working fine in Chrome and Edge. When WMS-t is loaded the time slider always displays one day minus, eg.

![image](https://user-images.githubusercontent.com/48727502/174041666-b6f8e293-1b31-4c29-8917-445c3fd6b1cc.png)

instead of correct

![image](https://user-images.githubusercontent.com/48727502/174041725-6d4d2b16-0580-4815-bccb-20d3717306af.png)

which is in the dropdown.

**To Reproduce**
1. Go to Datasources panel and add WMS by url, eg. EVI layer from
https://eo.lesprojekt.cz/geoserver/nemecek/wms?service=WMS&version=1.3.0&request=GetCapabilities
2. See the date in the time slider in layer manager, it should be 2022-03-16, but it is 2022-03-15
3. When the date is clicked and the dropdown opens, the correct date is in there.

**Comment by jmacura** [comment] 2022-06-16 11:10
I am aware of this. Didn't know that the issue is specific to Firefox though.
In my opinion, the problem is a conversion of a "midnight" date YYYY-MM-DDT00:00:000 to user's locale (which creates an hour or more shift into another day). Have to investigate further..

**Comment by jmacura** [comment] 2022-06-24 08:48
Resolved in #3139

**Closed by jmacura** 2022-06-24 08:48 UTC
Labels: bug, LayerSources
