### ISSUE TITLE
Duplicate layer list is created after adding a new layer without providing a folder name

### ISSUE THREAD

**Issue by DailisLangovskis** [hslayers/hslayers-ng#1427] opened 2020-12-28 11:18 UTC
![](https://user-images.githubusercontent.com/46564459/103010445-0db3a580-4541-11eb-9a6f-961667dddc40.png)

**Comment by raitisbe** [comment] 2020-12-30 10:34
Closing due to duplicate of https://github.com/hslayers/hslayers-ng/issues/1431

**Closed by raitisbe** 2020-12-30 10:34 UTC
Labels: bug
